version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/localhost/5444; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 8080'
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes:
      - ./logs_all:/app/logs_all
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 2s
      timeout: 5s
      retries: 20
    restart: always